// <auto-generated />
using APIControllerPostManPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIControllerPostManPractice.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIControllerPostManPractice.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int(10)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Discontinued = false,
                            Name = "Mixer",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -2,
                            Discontinued = false,
                            Name = "Rice Cooker",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -3,
                            Discontinued = false,
                            Name = "Wrench Set",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -4,
                            Discontinued = false,
                            Name = "Floor Jack",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -5,
                            Discontinued = false,
                            Name = "Screwdriver",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -6,
                            Discontinued = false,
                            Name = "Table",
                            Quantity = 2
                        },
                        new
                        {
                            ID = -7,
                            Discontinued = false,
                            Name = "Chair",
                            Quantity = 3
                        },
                        new
                        {
                            ID = -8,
                            Discontinued = true,
                            Name = "Sofa",
                            Quantity = 1
                        },
                        new
                        {
                            ID = -9,
                            Discontinued = false,
                            Name = "Cupboard",
                            Quantity = 10
                        },
                        new
                        {
                            ID = -10,
                            Discontinued = false,
                            Name = "Hummer",
                            Quantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
